import { ITeam } from 'src/tournaments/models/team.interface';

export const teams: ITeam[] = [
  { name: 'Uruguay' },
  { name: 'Mexico' },
  { name: 'South Africa' },
  { name: 'French' },
  { name: 'Argentina' },
  { name: 'Republic of Korea' },
  { name: 'Greece' },
  { name: 'Nigeria' },
  { name: 'USA' },
  { name: 'England' },
  { name: 'Slovenia' },
  { name: 'Algeria' },
  { name: 'Germany' },
  { name: 'Ghana' },
  { name: 'Australia' },
  { name: 'Serbia' },
  { name: 'Netherlans' },
  { name: 'Japan' },
  { name: 'Denmark' },
  { name: 'Cameroon' },
  { name: 'Paraguay' },
  { name: 'Slovakia' },
  { name: 'New Zealand' },
  { name: 'Italy' },
  { name: 'Brasil' },
  { name: 'Portugal' },
  { name: 'Ivory Coast' },
  { name: 'DPR of Korea' },
  { name: 'Spain' },
  { name: 'Chile' },
  { name: 'Switzerland' },
  { name: 'Honduras' },
];
