import { ITournament } from 'src/tournaments/models/tournament.interface';
import { QatarTeams } from '../teams/qatarTeamsEnum';

export const tournaments: ITournament[] = [
  {
    name: 'FIFA World Cup Qatar 2022',
    teams: [
      { name: QatarTeams.QATAR },
      { name: QatarTeams.ECUADOR },
      { name: QatarTeams.SENEGAL },
      { name: QatarTeams.NETHERLANDS },
      { name: QatarTeams.ENGLAND },
      { name: QatarTeams.IRAN },
      { name: QatarTeams.USA },
      { name: QatarTeams.WALES },
      { name: QatarTeams.ARGENTINA },
      { name: QatarTeams.SAUDI_ARABIA },
      { name: QatarTeams.MEXICO },
      { name: QatarTeams.POLAND },
      { name: QatarTeams.FRANCE },
      { name: QatarTeams.AUSTRALIA },
      { name: QatarTeams.DENMARK },
      { name: QatarTeams.TUNISIA },
      { name: QatarTeams.SPAIN },
      { name: QatarTeams.COSTA_RICA },
      { name: QatarTeams.GERMANY },
      { name: QatarTeams.JAPAN },
      { name: QatarTeams.BELGIUM },
      { name: QatarTeams.CANADA },
      { name: QatarTeams.MOROCCO },
      { name: QatarTeams.CROATIA },
      { name: QatarTeams.BRAZIL },
      { name: QatarTeams.SERBIA },
      { name: QatarTeams.SWITZERLAND },
      { name: QatarTeams.CAMEROON },
      { name: QatarTeams.PORTUGAL },
      { name: QatarTeams.GHANA },
      { name: QatarTeams.URUGUAY },
      { name: QatarTeams.SOUTH_KOREA },
      ,
    ],
  },
];
