import { PhaseOptions } from 'src/tournaments/entities/phase.entity';
import { IMatch } from 'src/tournaments/models/match.interface';

export const matches: IMatch[] = [
  {
    local: 'South Africa',
    visit: 'Mexico',
    goalsLocal: 1,
    goalsVisit: 1,
    groupStageName: 'A',
  },
  {
    local: 'Uruguay',
    visit: 'French',
    goalsLocal: 0,
    goalsVisit: 0,
    groupStageName: 'A',
  },
  {
    local: 'Republic of Korea',
    visit: 'Greece',
    goalsLocal: 2,
    goalsVisit: 0,
    groupStageName: 'B',
  },
  {
    local: 'Argentina',
    visit: 'Nigeria',
    goalsLocal: 1,
    goalsVisit: 0,
    groupStageName: 'B',
  },
  {
    local: 'England',
    visit: 'USA',
    goalsLocal: 1,
    goalsVisit: 1,
    groupStageName: 'C',
  },
  {
    local: 'Algeria',
    visit: 'Slovenia',
    goalsLocal: 0,
    goalsVisit: 1,
    groupStageName: 'C',
  },
  {
    local: 'Serbia',
    visit: 'Ghana',
    goalsLocal: 0,
    goalsVisit: 1,
    groupStageName: 'D',
  },
  {
    local: 'Germany',
    visit: 'Australia',
    goalsLocal: 4,
    goalsVisit: 0,
    groupStageName: 'D',
  },
  {
    local: 'Netherlans',
    visit: 'Denmark',
    goalsLocal: 2,
    goalsVisit: 0,
    groupStageName: 'E',
  },
  {
    local: 'Japan',
    visit: 'Cameroon',
    goalsLocal: 1,
    goalsVisit: 0,
    groupStageName: 'E',
  },
  {
    local: 'Italy',
    visit: 'Paraguay',
    goalsLocal: 1,
    goalsVisit: 1,
    groupStageName: 'F',
  },
  {
    local: 'New Zealand',
    visit: 'Slovakia',
    goalsLocal: 1,
    goalsVisit: 1,
    groupStageName: 'F',
  },
  {
    local: 'Ivory Coast',
    visit: 'Portugal',
    goalsLocal: 0,
    goalsVisit: 0,
    groupStageName: 'G',
  },
  {
    local: 'Brasil',
    visit: 'DPR of Korea',
    goalsLocal: 2,
    goalsVisit: 1,
    groupStageName: 'G',
  },
  {
    local: 'Honduras',
    visit: 'Chile',
    goalsLocal: 0,
    goalsVisit: 1,
    groupStageName: 'H',
  },
  {
    local: 'Spain',
    visit: 'Switzerland',
    goalsLocal: 0,
    goalsVisit: 1,
    groupStageName: 'H',
  },
  {
    local: 'South Africa',
    visit: 'Uruguay',
    goalsLocal: 0,
    goalsVisit: 3,
    groupStageName: 'A',
  },
  {
    local: 'Argentina',
    visit: 'Republic of Korea',
    goalsLocal: 4,
    goalsVisit: 1,
    groupStageName: 'B',
  },
  {
    local: 'Greece',
    visit: 'Nigeria',
    goalsLocal: 2,
    goalsVisit: 1,
    groupStageName: 'B',
  },
  {
    local: 'French',
    visit: 'Mexico',
    goalsLocal: 0,
    goalsVisit: 2,
    groupStageName: 'A',
  },
  {
    local: 'Germany',
    visit: 'Serbia',
    goalsLocal: 0,
    goalsVisit: 1,
    groupStageName: 'D',
  },
  {
    local: 'Slovenia',
    visit: 'USA',
    goalsLocal: 2,
    goalsVisit: 2,
    groupStageName: 'C',
  },
  {
    local: 'England',
    visit: 'Algeria',
    goalsLocal: 0,
    goalsVisit: 0,
    groupStageName: 'C',
  },
  {
    local: 'Netherlans',
    visit: 'Japan',
    goalsLocal: 1,
    goalsVisit: 0,
    groupStageName: 'E',
  },
  {
    local: 'Ghana',
    visit: 'Australia',
    goalsLocal: 1,
    goalsVisit: 1,
    groupStageName: 'D',
  },
  {
    local: 'Cameroon',
    visit: 'Denmark',
    goalsLocal: 1,
    goalsVisit: 2,
    groupStageName: 'E',
  },
  {
    local: 'Slovakia',
    visit: 'Paraguay',
    goalsLocal: 0,
    goalsVisit: 2,
    groupStageName: 'F',
  },
  {
    local: 'Italy',
    visit: 'New Zealand',
    goalsLocal: 1,
    goalsVisit: 1,
    groupStageName: 'F',
  },
  {
    local: 'Brasil',
    visit: 'Ivory Coast',
    goalsLocal: 3,
    goalsVisit: 1,
    groupStageName: 'G',
  },
  {
    local: 'Portugal',
    visit: 'DPR of Korea',
    goalsLocal: 7,
    goalsVisit: 0,
    groupStageName: 'G',
  },
  {
    local: 'Chile',
    visit: 'Switzerland',
    goalsLocal: 1,
    goalsVisit: 0,
    groupStageName: 'H',
  },
  {
    local: 'Spain',
    visit: 'Honduras',
    goalsLocal: 2,
    goalsVisit: 0,
    groupStageName: 'H',
  },
  {
    local: 'Mexico',
    visit: 'Uruguay',
    goalsLocal: 0,
    goalsVisit: 1,
    groupStageName: 'A',
  },
  {
    local: 'French',
    visit: 'South Africa',
    goalsLocal: 1,
    goalsVisit: 2,
    groupStageName: 'A',
  },
  {
    local: 'Nigeria',
    visit: 'Republic of Korea',
    goalsLocal: 2,
    goalsVisit: 2,
    groupStageName: 'B',
  },
  {
    local: 'Greece',
    visit: 'Argentina',
    goalsLocal: 0,
    goalsVisit: 2,
    groupStageName: 'B',
  },
  {
    local: 'Slovenia',
    visit: 'England',
    goalsLocal: 0,
    goalsVisit: 1,
    groupStageName: 'C',
  },
  {
    local: 'USA',
    visit: 'Algeria',
    goalsLocal: 1,
    goalsVisit: 0,
    groupStageName: 'C',
  },
  {
    local: 'Ghana',
    visit: 'Germany',
    goalsLocal: 0,
    goalsVisit: 1,
    groupStageName: 'D',
  },
  {
    local: 'Australia',
    visit: 'Serbia',
    goalsLocal: 2,
    goalsVisit: 1,
    groupStageName: 'D',
  },
  {
    local: 'Slovakia',
    visit: 'Italy',
    goalsLocal: 3,
    goalsVisit: 2,
    groupStageName: 'F',
  },
  {
    local: 'Paraguay',
    visit: 'New Zealand',
    goalsLocal: 0,
    goalsVisit: 0,
    groupStageName: 'F',
  },
  {
    local: 'Denmark',
    visit: 'Japan',
    goalsLocal: 1,
    goalsVisit: 3,
    groupStageName: 'E',
  },
  {
    local: 'Cameroon',
    visit: 'Netherlans',
    goalsLocal: 1,
    goalsVisit: 2,
    groupStageName: 'E',
  },
  {
    local: 'Portugal',
    visit: 'Brasil',
    goalsLocal: 0,
    goalsVisit: 0,
    groupStageName: 'G',
  },
  {
    local: 'DPR of Korea',
    visit: 'Ivory Coast',
    goalsLocal: 0,
    goalsVisit: 3,
    groupStageName: 'G',
  },
  {
    local: 'Chile',
    visit: 'Spain',
    goalsLocal: 1,
    goalsVisit: 2,
    groupStageName: 'H',
  },
  {
    local: 'Switzerland',
    visit: 'Honduras',
    goalsLocal: 0,
    goalsVisit: 0,
    groupStageName: 'H',
  },
];

export const final_matches = [
  // Final Phase
  {
    local: 'Uruguay',
    visit: 'Republic of Korea',
    goalsLocal: 2,
    goalsVisit: 1,
    phase: PhaseOptions.EIGHTH_FINAL,
  },
  {
    local: 'USA',
    visit: 'Ghana',
    goalsLocal: 1,
    goalsVisit: 2,
    phase: PhaseOptions.EIGHTH_FINAL,
  },
  {
    local: 'Argentina',
    visit: 'Mexico',
    goalsLocal: 3,
    goalsVisit: 1,
    phase: PhaseOptions.EIGHTH_FINAL,
  },
  {
    local: 'Germany',
    visit: 'England',
    goalsLocal: 4,
    goalsVisit: 1,
    phase: PhaseOptions.EIGHTH_FINAL,
  },
  {
    local: 'Netherlans',
    visit: 'Slovakia',
    goalsLocal: 2,
    goalsVisit: 1,
    phase: PhaseOptions.EIGHTH_FINAL,
  },
  {
    local: 'Brasil',
    visit: 'Chile',
    goalsLocal: 3,
    goalsVisit: 0,
    phase: PhaseOptions.EIGHTH_FINAL,
  },
  {
    local: 'Paraguay',
    visit: 'Japan',
    goalsLocal: 0,
    goalsVisit: 0,
    penalsLocal: 5,
    penalsVisit: 3,
    phase: PhaseOptions.EIGHTH_FINAL,
  },
  {
    local: 'Spain',
    visit: 'Portugal',
    goalsLocal: 1,
    goalsVisit: 0,
    phase: PhaseOptions.EIGHTH_FINAL,
  },
  {
    local: 'Uruguay',
    visit: 'Ghana',
    goalsLocal: 1,
    goalsVisit: 1,
    penalsLocal: 4,
    penalsVisit: 2,
    phase: PhaseOptions.QUARTERS_FINAL,
  },
  {
    local: 'Netherlans',
    visit: 'Brasil',
    goalsLocal: 2,
    goalsVisit: 1,
    phase: PhaseOptions.QUARTERS_FINAL,
  },
  {
    local: 'Argentina',
    visit: 'Germany',
    goalsLocal: 0,
    goalsVisit: 4,
    phase: PhaseOptions.QUARTERS_FINAL,
  },
  {
    local: 'Paraguay',
    visit: 'Spain',
    goalsLocal: 0,
    goalsVisit: 1,
    phase: PhaseOptions.QUARTERS_FINAL,
  },
  {
    local: 'Uruguay',
    visit: 'Netherlans',
    goalsLocal: 2,
    goalsVisit: 3,
    phase: PhaseOptions.SEMI_FINAL,
  },
  {
    local: 'Germany',
    visit: 'Spain',
    goalsLocal: 0,
    goalsVisit: 1,
    phase: PhaseOptions.SEMI_FINAL,
  },
  {
    local: 'Uruguay',
    visit: 'Germany',
    goalsLocal: 2,
    goalsVisit: 3,
    phase: PhaseOptions.THITD_AND_FOURTH,
  },
  {
    local: 'Netherlans',
    visit: 'Spain',
    goalsLocal: 0,
    goalsVisit: 1,
    phase: PhaseOptions.FINAL,
  },
];
